# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none


pool:
  vmImage: ubuntu-latest

parameters:
  - name: environment
    default: 'dev'
    values:
      - dev
      - qa
      - prod  

steps: 
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
      backendServiceArm: 'narayanServiceConnection'
      backendAzureRmStorageAccountName: 'mishrastorage'
      backendAzureRmContainerName: 'tfstate'
      backendAzureRmKey: 'monolithic.tfstate'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'validate'
      workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'




  
